### ISSUE TITLE
Error on 1.19.3

### ISSUE THREAD

**Issue by sternschnaube** [GrigLog/RoughlyEnoughLootTables#2]
Hello, I was looking again over it and I got this error from the server log:
I am not able to see any loot tables.

**First:**
[REI] ReltServer of ReltServer [roughly_enough_loot_tables] plugin failed to reloadable-plugin/EntryTypeRegistryImpl/!
java.lang.ExceptionInInitializerError: null
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4) ~[?:?]
	at griglog.relt.rei_plugin.ReltServer.registerEntryTypes(ReltPlugin.kt:37) ~[RoughlyEnoughLootTables-1.19-1.0.jar:?]
	at me.shedaniel.rei.impl.common.entry.type.EntryTypeRegistryImpl.acceptPlugin(EntryTypeRegistryImpl.java:56) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:72) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:340) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:198) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:330) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:196) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:328) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:114) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$onInitialize$3(RoughlyEnoughItemsCore.java:144) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.Util.waitAndApply(Util:948) ~[?:?]
	at net.minecraft.util.Util.waitAndApply(Util:936) ~[?:?]
	at net.minecraft.server.Main.main(Main:150) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[minecraft_server.jar:0.11.1]
Caused by: java.lang.RuntimeException: Cannot load class me.shedaniel.rei.api.client.entry.renderer.EntryRenderer in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at griglog.relt.rei_plugin.TableEntryDef.<clinit>(TableEntryDef.kt:28) ~[RoughlyEnoughLootTables-1.19-1.0.jar:?]
	... 22 more

**A bit later:**
[REI] ReltServer of ReltServer [roughly_enough_loot_tables] plugin failed to reloadable-plugin/EntryTypeRegistryImpl/!
java.lang.NoClassDefFoundError: Could not initialize class griglog.relt.rei_plugin.TableEntryDef
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4) ~[?:?]
	at griglog.relt.rei_plugin.ReltServer.registerEntryTypes(ReltPlugin.kt:37) ~[RoughlyEnoughLootTables-1.19-1.0.jar:?]
	at me.shedaniel.rei.impl.common.entry.type.EntryTypeRegistryImpl.acceptPlugin(EntryTypeRegistryImpl.java:56) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:72) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:340) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:198) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:330) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:196) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:328) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:114) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$onInitialize$3(RoughlyEnoughItemsCore.java:144) ~[RoughlyEnoughItems-10.0.581.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by GrigLog** [comment]
Should work now

**Comment by venaminecraft** [comment]
Thank you @GrigLog.
Could you provie please a build for 1.20.1? 😊

**Comment by GrigLog** [comment]
I am too lazy to make updates for every tiny MC version that is about to come out in this year. Its no fun and I dont even play the latest version myself. So I dont think I will build for 1.20 until its finished

**Comment by venaminecraft** [comment]
Looking forward to it - this can be closed now 😊
